### ISSUE TITLE
Nuxt support?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [logaretm/villus#10]
This looks like a neat library! I want to get rid of `vue-apollo` because of all the cruft it comes with.

Will I be able to use this with [Nuxt](https://nuxtjs.org)?

**Comment by logaretm** [comment]
You can use it already with Nuxt, but doing SSR is kinda tricky since Nuxt only allows page components to do so.

You can use the client instance to fetch your queries in `asyncData`

https://logaretm.github.io/villus/guide/using-the-client-manually.html#executing-queries

**Comment by dpschen** [comment]
Follow up:

I guess it can now easily be used together with the [fetch hook](https://nuxtjs.org/docs/2.x/features/data-fetching/#the-fetch-hook), or possibly even better with [useFetch](https://composition-api.nuxtjs.org/helpers/useFetch)
