### ISSUE TITLE
client.executeSubscription docs

### ISSUE THREAD

**Issue by mxrlkn** [logaretm/villus#101]
At https://villus.logaretm.com/api/client#subscriptions there's this snippet:

```
const observable = client.executeSubscription({
  query: 'your subscription query',
  variables: {
    // any variables
  },
});

observable.subscribe({
  next(response) {
    // handle incoming data
  },
  // eslint-disable-next-line
  error(err) {
    // Handle errors
  },
});
```

It looks like `client.executeSubscription` returns a promise which then returns the subscribe function.

I had to await `client.executeSubscription` first:

```
const observable = await client.executeSubscription({
  query: 'your subscription query',
  variables: {
    // any variables
  },
});

observable.subscribe({
  next(response) {
    // handle incoming data
  },
  // eslint-disable-next-line
  error(err) {
    // Handle errors
  },
});
```

Either the docs are wrong and it's supposed to return a promise, or the `client.executeSubscription` is working incorrectly.

great lib btw 👍

**Comment by logaretm** [comment]
Thank you for bringing this up, the docs were outdated. Should be updated shortly!
