### ISSUE TITLE
Interceptor/Middlewares 

### ISSUE THREAD

**Issue by dualmacops** [logaretm/villus#103]
First, congrats on this piece of software.
After reading this post (https://logaretm.com/blog/2020-01-11-announcing-villus/) I decided to start my project with villus instead of vue apollo.

The app would mostly be behind authentication via JWT.
**My problem is that as far I see I would have to handle the renewal of the token/handling the exception of expired token on every request.**
It would be nice to have Interceptors like axios to abstract the jwt renewal/exeption hanling implementation to independent functions that are used on every request.

Thanks in advance.

**Comment by logaretm** [comment]
Oh, looks like I forgot add the `afterQuery` response argument to the docs, sorry about that.

I think the plugins API offer enough to do that, like using `afterQuery` could work here:

```js
import { useClient, useMutation, defaultPlugins } from 'villus';

const client = useClient({
  url: '/graphql',
  use: [refreshAuth, ...defaultPlugins()]
});

const { execute } = useMutation(RefreshToken);

function refreshAuth({ afterQuery }) {
  // ...
  afterQuery((result, { response }) => {
    if (response.status === 403) {
      // call API to refresh token with either client.executeMutaiton or execute from the useMutation
    }
  });
  // ...
}
```

LMK if its not working out for you

**Comment by dualmacops** [comment]
Yes, looks like the afterQuery would work great if the server returns that the token is expired.

But it would also be nice to have a **beforeQuery** that checks if the token is expired before sending the request and refreshing it before sending the query (saving 1 roundtrip time).

**Comment by logaretm** [comment]
Well there isn't a point to introduce the `beforeQuery` hook as the plugin function acts as one.

```
const client = useClient({
  url: '/graphql',
  use: [refreshAuth, ...defaultPlugins()]
});

async function refreshAuth({ opContext ) {
  if (tokenExpired) {
    // refresh token
    opContext.headers['Authorization'] = await someFunThatGetsTheNewToken();
  }
}
```
