### ISSUE TITLE
Access GraphQL errors when HTTP status code is 500

### ISSUE THREAD

**Issue by lewebsimple** [logaretm/villus#104]
Is there a way to prevent Villus from imposing a `[Network] Internal Server Error` when the GraphQL server responds with a 500 status code ?
When I configure the server to send 200 on error instead, I can access the GraphQL errors returned from the combined error just fine.

Maybe add some kind of custom error handling / formatting feature ?

**Comment by logaretm** [comment]
You could access the internal errors with `error.graphqlErrors` which are the same ones in the GraphQL response, otherwise if it is not a GraphQL error it will reside in `error.networkError`

Is this not the case?

**Comment by lewebsimple** [comment]
When the server uses http status code 500, Villus gobbles everything up as a network error.

**Comment by logaretm** [comment]
Which plugins are you using?

**Comment by lewebsimple** [comment]
subscriptions, multipart, idbCache (custom indexeddb cache), dedup and batch

**Comment by logaretm** [comment]
Oh, the `batch` is culprit, the `fetch` plugin was updated to support this use case.\

Thank you for reporting this, will fix it later today.

**Comment by logaretm** [comment]
Published with `rc.13`
