### ISSUE TITLE
Should the ClientPluginOperation type be exported?

### ISSUE THREAD

**Issue by thalesagapito** [logaretm/villus#105]
I'm trying to create a strongly typed cache plugin for my use case, using cache.ts as a starting point.
After updating the type imports to point to villus instead of './types', I'm having the following error pop up:
`Module '"../../node_modules/villus/dist/villus"' declares 'ClientPluginOperation' locally, but it is not exported.ts(2459)`
Is this expected? Currently it's not a problem for me, I can just move on without typing the `setCacheResult` args, but I thought I'd point this out.

**Comment by logaretm** [comment]
Could you create a repo with this issue? I realize there are potentially a lot of types that should be exported but I don't want to expose types that might change in non-major releases.

**Comment by thalesagapito** [comment]
https://github.com/thalesagapito/villus-cache-plugin-repro

**Comment by logaretm** [comment]
Well, from what I gather you could send the parts you need like the `key` to the cache functions you use. But I think some types need to be exposed never the less, so should be up in `rc.15` shortly
