### ISSUE TITLE
Re-fetching and caching conflict

### ISSUE THREAD

**Issue by connorshea** [logaretm/villus#108]
The default strategy of caching a query conflicts with what's suggested by [the re-fetching documentation](https://villus.logaretm.com/guide/queries#re-fetching-queries).

I ran into this problem with my code, which looks like this:

```typescript
// EventCard.vue
setup() {
  const { execute } = useMutation(DeleteEventDocument);
  const deleteEvent = () => {
    execute({ id: props.event.id }).then(() => {
      // Refresh the events list after the event has been deleted.
      context.emit('refresh');
    });
  };
}
```

And then in the parent component, I have an `@refresh="execute"` on the EventCard:

```vue
// Activity.vue
<template>
  <div>
    <template v-for="event in data.activity.nodes">
      <EventCard :event="event" :key="event.id" @refresh="execute"/>
    </template>
  </div>
</template>

<script lang="ts">
import { ActivityFeedDocument } from '@/generated/graphql';
import { computed, defineComponent } from '@vue/composition-api';
import { useQuery } from 'villus';
import EventCard from '@/components/EventCard.vue';

export default defineComponent({
  name: 'Activity',
  components: {
    EventCard
  },
  setup(_props, context) {
    const { data, execute } = useQuery({
      query: ActivityFeedDocument
    });

    return { data, execute };
  }
});
</script>
```

So when I emit the event from the, I _expect_ that it would re-fetch the query because that's what the docs seem to suggest would happen. Due to the default caching policy, this does not happen.

I'd like there to be a way to pass a cache policy to execute, e.g. `execute({ cachePolicy: 'network-only' })` (or maybe there already is?), and I think a warning should be added to the documentation on re-fetching about this problem to clarify that this will require a non-default cache policy for it to work. I got stuck on it for a good while.

**Comment by logaretm** [comment]
You already can, please check [this](https://villus.logaretm.com/guide/queries#on-each-execute-call-level).

Will close this, if it doesn't work for you, let me know and I will re-open
