### ISSUE TITLE
Can't execute multiple queries in a single Vue component

### ISSUE THREAD

**Issue by Areskul** [logaretm/villus#114]
I have tried to execute  multiple queries in a single component but .... 
```ts
{ data , execute } = useQuery({ 
  query: MY_QUERY
})
```
data and execute or const.

Am I missing something ?
Should I allow renaming const in my tsconfig ?
Is this behavior done on purpose ?

**Comment by logaretm** [comment]
If you want to call `useQuery` multiple times in the same component, then you have to rename your destructed properties, it is not "on purpose" it's how JavaScript works.

Here is a couple of suggestions:

**Renaming destructed properties:**

```js
const { data: postsData, execute: fetchPosts } = useQuery({
  query: PostsQuery
})

// postsData.value;
// fetchPosts();

const { data: authorsData, execute: fetchAuthors } = useQuery({
  query: AuthorsQuery
});

// authorsData.value;
// fetchAuthors();
```

**Without destructing:**

```js
const posts = useQuery({
  query: PostsQuery
})

// posts.data.value;
// posts.execute();

const authors = useQuery({
  query: AuthorsQuery
})

// authors.data.value;
// authors.execute();
```

**Comment by Areskul** [comment]
Woaw, I am definitly missing some knowledge in javascript.

Thank you @logaretm for your time, and this incredible graphql cli.
