### ISSUE TITLE
vue.defineComponent is not a function

### ISSUE THREAD

**Issue by h0merjam** [logaretm/villus#125]
Hi,

I'm having an issue with Nuxt. I'm 99.9% sure I'm doing something idiotic. Here's my setup:

```js
// plugins/villus.js

import { cache, dedup, useClient } from 'villus';
import { batch } from '@villus/batch';
import { multipart } from '@villus/multipart';
import { onGlobalSetup } from '@nuxtjs/composition-api';
import fetch from 'cross-fetch';

export default ({ $config }, inject) => {
  onGlobalSetup(() => {
    const villus = useClient({
      url: $config.BACKEND_GRAPHQL_URL,
      use: [cache(), dedup(), batch({ fetch }), multipart()],
    });
    inject('villus', villus);
  });
};

```

```js
// nuxt.config.js

export default {
...
  plugins: ['~/plugins/villus'],
...
  buildModules: [
    '@nuxt/typescript-build',
    '@nuxtjs/composition-api/module',
  ],
...
}
```

Here's what I get:

<img width="1359" alt="Screenshot 2021-05-26 at 12 54 36" src="https://user-images.githubusercontent.com/1055769/119655489-8c2eaf00-be21-11eb-94ef-17d2057c63d7.png">

Any help would be really appreciated! 

Thanks

**Comment by h0merjam** [comment]
I've just noticed that Vue 2 support has been dropped as of rc17!

Is there any suggested workaround/solution for Nuxt users apart from reverting to rc16?

**Comment by logaretm** [comment]
Sorry about this, no workarounds. This was imminent as half of the codebase didn't work with Vue 2 anyways (the HOC components)

I will add a warning to the docs

**Comment by fsmonter** [comment]
Hi @logaretm. Was wondering if this means that currently, villus does not support Nuxt.js.
