### ISSUE TITLE
Can latest version use Options API? 

### ISSUE THREAD

**Issue by IvanSGurdian** [logaretm/villus#127]
I just started using Villus since I'm building a simple app, but I find myself liking the Options API more than Composition, I see the docs show the usage of the library inside the `setup()` function.

I was wondering if this lates version can be used with the Options API and if so, is there any example of how to declare and execute a query with it?

**Comment by logaretm** [comment]
You could in theory do it with the `client` manually, but there isn't any helpers to do it within your script without the composition API.

You may use the `Query` or `Mutation` components as well, but there is no plan for it to be used with the Options API.
