### ISSUE TITLE
Respect type definitions for executeQuery

### ISSUE THREAD

**Issue by JarvisH** [logaretm/villus#128]
In the documentation https://villus.logaretm.com/guide/typescript-codgen/#using-generated-queries it shows the following code example:

```js
const { data } = useQuery<PostsQuery, PostsQueryVariables>({
  query: Posts
  variables: {
    // variables are now typed as PostsQueryVariables
  },
});

data.value; // is now typed as PostsQuery type!
```

This does not appear to work when using `executeQuery` instead of `useQuery`.  In the `villus.d.ts` file the following signature is found:

```ts
executeQuery<TData = any, TVars = QueryVariables>(operation: OperationWithCachePolicy<TData, TVars>, queryContext?: QueryExecutionContext): Promise<OperationResult>;
```

Is it as simple as adding `TData` to `OperationResult`?

**Comment by logaretm** [comment]
Thanks for reporting this, yes you are right it is as you suggested. You should find the updated types in `rc.18`

**Comment by JarvisH** [comment]
Thank you for the quick fix, you rock!
