### ISSUE TITLE
Nuxt + Villus 

### ISSUE THREAD

**Issue by DregondRahl** [logaretm/villus#129]
I was using Nuxt + Villus for a while, but after an update it started throwing error where it was looking for toRefs and such in vue. Since Nuxt is Vue2 I believe the rc.17 release is the cause of this. 

`export 'toRefs' was not found in 'vue'  `

The project im working on has @nuxtjs/composition-api, but its still not working anymore.  Any suggestions on getting compatibility with composition api?

**Comment by logaretm** [comment]
Villus dropped the `vue-demi` compatibility that allowed this, if you want to use it with Vue 2 then use `rc.16`. No plans to support both releases anymore.
