### ISSUE TITLE
Villius with vue 2

### ISSUE THREAD

**Issue by stephanedemotte** [logaretm/villus#13]
Hello, can we use villus in vue 2 without composition api ?

If yes, can you provide a example ?

Thanks !!

**Comment by logaretm** [comment]
You can use the `0.2.4` release, it doesn't have all the features but it is still viable.

**Comment by hipertracker** [comment]
Here is an example for Vue 2 https://gist.github.com/hipertracker/0682f2c88774cc5274c18f36db2e0a64
