### ISSUE TITLE
Type inference not working with `typed-document-node`

### ISSUE THREAD

**Issue by essarn** [logaretm/villus#130]
I'm using `villus: 1.0.0-rc.18` with Nuxt and the composition api. The type inference when providing a generated document to use functions is not working as stated in the docs.

Consider this mock source file that has been generated:
``` graphql
mutation SendMagicLink($email: String!) {
  sendMagicLink(input: { email: $email, audience: "admin" }) {
    sentTo
    expiresIn
  }
}
```

And then using the generated document...

```typescript
const { data, execute } = useMutation(SendMagicLinkDocument)
```

In this case, both `data.vaue` and `execute.data` would be types as `any` which is incorrect. Note that the types can be corrected by adding the generic types to the function but this should not be needed as peer the docs.

**Comment by logaretm** [comment]
Vue 2 support (Including Nuxt, and vue/composition API) has been dropped in RC.16, AFAIK it should be working fine in Vue 3 projects.

Can you downgrade and see if the issue persists?

**Comment by essarn** [comment]
The problem persists after having downgraded to `villus": 1.0.0-rc.15` unfortunately. I have tried with both the ´Volar´ and ´Vetur´ extension for VSCode but the no change there. Also I'm using ´Remote-SSH´ but that shouldn't have any impact right?

**Comment by logaretm** [comment]
I use `villus` in a lot of projects and didn't encounter this. It's probably something wrong with your setup.

Try to reproduce this issue in a new repo or codesandbox and I will take a look, but closing as hardly anything changed between the recent releases.

**Comment by essarn** [comment]
> I use `villus` in a lot of projects and didn't encounter this. It's probably something wrong with your setup.

Yes, you are probably right. Tested with a clean `Vite` project and it works. 
Will be waiting for `Nuxt 3` to be released which hopefully should  be soon.

Thanks for the help.

**Comment by essarn** [comment]
Hi again, just giving an update. Everything now working as expected with `villus: 1.0.0-rc.15` after doing a clean install of the `node_modules` folder.
