### ISSUE TITLE
How to add a plugin to client after it was created

### ISSUE THREAD

**Issue by elC0mpa** [logaretm/villus#131]
First of all I would like to thank you for this great library, mainly because, as you said, it is pretty simple, and could be used in most of the graphQL clients.
I need to do excatly [this](https://villus.logaretm.com/guide/plugins/#example:-adding-authorization-headers), but the problem is that I configured the client in ```App.vue``` as you suggest, but I get the token from the server after that, so I suppose that I can´t call ```useClient``` method again. Basically what I need to know is how to setUp the header plugin after the client was created. Thanks in advance

**Comment by logaretm** [comment]
Plugins are evaluated every time you send a query. So you could setup a ref or a store with the token value and have the plugin evaluate at runtime, so something like this:

```js
import { ref } from 'vue';

// update this from anywhere in your code
const authToken = ref('');

function authPlugin({ opContext }) {
  if (authToken.value) {
    opContext.headers.Authorization = `Bearer ${authToken}`;
  }
}

```

Once you set it, all the subsequent queries/mutations should have the header applied
