### ISSUE TITLE
useQuery on user click or trigger and not on component load  [question]

### ISSUE THREAD

**Issue by orenmizr** [logaretm/villus#138]
was looking for a login example with villus. useQuery behind a function.. 
- since it is a hook it must be on root i suppose
- but it executes when components loads

how can i execute login request only on button click ? what is the best practice here ? 

// login form:
```
// must be on root to work
const { data, execute } = useQuery({
				query: `{
					User(id: 123) {
						token
					}
				}
				`,
			});
			

// on form submit
if (valid) {
			// what goes here ?
			return { data };
...			
```

**Comment by logaretm** [comment]
Disable the [`fetchOnMount` option](https://villus.logaretm.com/api/use-query#query-options) and use the `execute` function to execute the query when needed:

```js
const { data, execute } = useQuery({
  fetchOnMount: false,
  query: `{
    User(id: 123) {
      token
    }
  }`,
});

function onSubmit() {
  if (valid {
    execute({
      variables: {
        // ...
      }
    })
  }
}
```

**Comment by orenmizr** [comment]
thanks. missed the false field on the docs. that's a good sane default. thanks for the quick response. much appropriated.
