### ISSUE TITLE
Use Cookies with Client and SubscriptionClient

### ISSUE THREAD

**Issue by V3lop5** [logaretm/villus#140]
Hi there,

I need `Client` and `SubscriptionClient` pass my cookies. I found issue #35 but the solution didn't work anymore.

I set up my connection according to your [Subscriptions Guide](https://villus.logaretm.com/guide/subscriptions):
```ts
this.subscriptionClient = new SubscriptionClient(`ws://${this.baseUrl}/subscriptions`, {});

this.gqlClient = createClient({
  url: `http://${this.baseUrl}/graphql`,
  use: [handleSubscriptions(op => this.subscriptionForwarder(op)), ...defaultPlugins()],
});
```

I think I need to configure the [Fetch Plugin](https://villus.logaretm.com/plugins/fetch). I found your [examples](https://villus.logaretm.com/guide/plugins#opcontext) for plugin configurations, but they didn't helped me understanding what to do. (Maybe because I'm a backend developer trying my first frontend/web project...)

Would be nice if you can provide an example and help me out! 

More background information about my problem:
I use cookie based session management in my project. 
The initial session cookie is retrieved by a REST-API. (Got that running with [axios](https://github.com/axios/axios).)
The value of my cookie will change over time. The response of graphql requests made by villus can contain a new session cookie. The updated cookie value needs to be passed to axios and fetch plugin (?) for future graphql requests.
The `SubscriptionClient` should be fine due to an never ending connection. It needs to pass the cookie only on connection setupt.

**Comment by logaretm** [comment]
Does your API have the same domain or is it a different one?

You can [configure the `fetch` options to include any credentials](https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters).

So with villus it is just a matter of adding a plugin to the chain:

```js
function authPlugin({ opContext }) {
  opContext.credentials = 'include';
}

// later in your setup
import { useClient, defaultPlugins } from 'villus';

useClient({
  url: '/graphql',
  use: [authPlugin, ...defaultPlugins()],
});
```

This will probably work for you. Let me know if it doesn't.
