### ISSUE TITLE
How to use in e.g. Pinia

### ISSUE THREAD

**Issue by MidasLamb** [logaretm/villus#149]
Hi, I'm pretty new to Vue3, and I'm wondering how I would need to go about invoking an API request using Villus in e.g. an action inside a Pinia Store?

It gives the following error:
![image](https://user-images.githubusercontent.com/14802865/151420115-f4ca4108-11fd-4be8-ab40-188fb2f4fc5e.png)

Even though I `useClient` in the Store right before the call.

If you could help me out I'd love to open a PR to update the documentation with an example as well

**Comment by logaretm** [comment]
Do you mind creating an example for this? you can use codesandbox or stackblitz and I will be happy to take a look.

**Comment by fanckush** [comment]
I don't think this is because of Pinia specifically, related: https://github.com/logaretm/villus/issues/146
the error is correlated to the yellow warning above which has something to do with `provide()`ing / `inject()`ing

**Comment by logaretm** [comment]
@fanckush You are right, when it comes to `provide`/`inject` many things could go wrong which is why I wanted to see how exactly the OP is using Pinia with `villus`.

I may add an official example this weekend to try to answer this.

**Comment by GavinXue** [comment]
@logaretm Thank you for your great work of villus first, it's awesome.
I have made this example here: https://codesandbox.io/s/mystifying-nobel-vy0r3x?file=/src/main.ts .
Using useQuery outside of setup will encounter this, and in pinia I only can import the villusClient to execute query. though it works , I also really like to useQuery api to manage the queries. Hope there is some solutions or some ideas to use useQuery outside of setup()

**Comment by logaretm** [comment]
Thanks to @GavinXue in #156 this is much easier to do if you plan to use `useQuery` and others in store actions. 

However Pinia offers an official composable way to do this. An official example was added: 

https://villus.logaretm.com/examples/state-store-pinia

**Comment by hipertracker** [comment]
Villus works with Vue 3, but I have a problem making it working with Vue 2  https://gist.github.com/hipertracker/3676ae8a5661f7d7423982188cc265fe

**Comment by logaretm** [comment]
@hipertracker Can you get that in a repo I can test?

**Comment by hipertracker** [comment]
> @hipertracker Can you get that in a repo I can test?

I was wrong, Vue 2 also works https://gist.github.com/hipertracker/0682f2c88774cc5274c18f36db2e0a64
