### ISSUE TITLE
How to use in nuxt3 <script setup> with useAsyncData()?

### ISSUE THREAD

**Issue by ayalon** [logaretm/villus#152]
I tried the villus client with nuxt3 and it basically worked. But I was unsure how to use it together with the new nuxt3 composable "useAsyncData()".

I was using it like that but its a bit a mess because useQuery() already returns reactive data.

```
<script setup lang="ts">
import {useQuery} from 'villus';
import { AllFilmsDocument } from "@/graphql/operations";

const { data } = await useAsyncData('films', async () => {
  const { data } = await useQuery({
    query: AllFilmsDocument,
  });
  return data.value;
})

const films = data.value.allFilms.films

</script>

```

Could someone give me some feed if this is correct or how it should / could be improved?

**Comment by logaretm** [comment]
This could be problematic since `useQuery` uses injections and you can't use injections outside of your setup function. So if it worked for you then it's probably because Nuxt ran the async function during setup, which isn't a good thing to rely on.

Instead you should call the `useQuery` earlier and use `execute` inside your `asyncData` function. I believe something like this should work but I haven't tried it myself:

```js
import {useQuery} from 'villus';
import { AllFilmsDocument } from "@/graphql/operations";

const { execute } = useQuery({
  query: AllFilmsDocument,
  fetchOnMount: false,
});

const { data, pending } = await useAsyncData('films', execute);
```

**Comment by ayalon** [comment]
Thanks for the example. I think the idea is great but unfortunatly it does not work. If I pass the promise function to userAsyncData() I get back a Proxy Object. It seems that it is not possible to resolve the Promise. I have no clue, wehre the issue is.

Maybe at some time you can try villus in a Nuxt 3 project and add an example.

**Comment by logaretm** [comment]
I think this way you are executing the query twice which isn't ideal, could you skip the `await` with `useQuery` and keep everything else as is?

**Comment by ayalon** [comment]
Yeah! This is the right solution i think! Thanks for your valuable help.

**Comment by furier** [comment]
I think a plugin should be created for this so villus would under the hood just use Nuxt3's `useFetch` or `useAsyncData` composable in stead of the `$fetch` api. So when configuring villus you would just say use that plugin in stead of the default one?
