### ISSUE TITLE
How to set headers after the client has been initialised ?

### ISSUE THREAD

**Issue by francelwebdev** [logaretm/villus#162]
Hello, how to set headers after the client has been initialised ?

**Comment by logaretm** [comment]
You can do this via `plugins` like this [Auth header example here](https://villus.logaretm.com/guide/plugins#example---adding-authorization-headers). 

Or you can also use `context` object while creating the query or mutation:

```js
const { execute } = useMutation(`mutation { test }`, {
  context: {
    headers: {
      'someheader': 'value'
    }
  }
});

const { execute } = useQuery({
  query: '{ test }',
  context: {
    headers: {
      someheader: 'value',
    },
  },
});
```

The latter approach isn't documented, I will make sure to add it.
