### ISSUE TITLE
how can i use makeFetchOptions

### ISSUE THREAD

**Issue by ZengDaWei** [logaretm/villus#163]
I want to use a custom fetch function, so I copied the code in the fetch.js file for custom modification, but I can't find the makeFetchOptions function, it seems it's not exported.

![image](https://user-images.githubusercontent.com/44629601/176330978-799cb6b2-5513-466c-a748-0c31c1b874f2.png)

**Comment by logaretm** [comment]
Sorry about the delay with this, you can do so now by importing it from `villus` in `2.0.1`.
