### ISSUE TITLE
TS4023: Exported variable has or is using name 'QueryExecutionOpts' from external module but cannot be named.

### ISSUE THREAD

**Issue by DaLukasTI** [logaretm/villus#176]
Hi,
Typescript server seems to have an issue with the d.ts file from the package.
In my IDE's (checked VSCode and webstorm) both seem to nag about  `QueryExecutionOpts` not being exported with following error:
`TS4023:` Exported variable 'useStoreName' has or is using name 'QueryExecutionOpts' from external module "/path/to/node_modules/villus/dist/villus" but cannot be named.`
However if I manually export this interface from the villus.d.ts file both IDE's are happy again. The weird part is the IDE keeps complaining but vue-tsc en building runs perfectly fine. 
I'll open a PR to export that interface aswel?

**Comment by logaretm** [comment]
Sure, feel free to PR it.

**Comment by DaLukasTI** [comment]
#177 should fix it :grin:

**Comment by DaLukasTI** [comment]
Closing as this was fixed in #177
