### ISSUE TITLE
Query normalization with `useSubscription`

### ISSUE THREAD

**Issue by imjasonmiller** [logaretm/villus#188]
Hey, great library!

Perhaps I am holding it wrong, but I was caught by surprise by the documentation mentioning that queries parsed with `gql` from `graphql-tag` [can be passed to `useQuery`](https://villus.logaretm.com/guide/queries/#with-graphql-tag), while this seems to work a bit different for `useSubscription`. 

While the API reference states a [`DocumentNode` can be passed](https://villus.logaretm.com/api/use-subscription/#usage) as well, I received that exact `DocumentNode` within the `subscriptionForwarder` by setting it up as described by [the guide](https://villus.logaretm.com/guide/subscriptions/). It looks like that will result in an error for `graphql-ws`'s client as it takes a `string` and no normalization is performed, unlike `useQuery`.

Is this intended behavior or would it be possible to apply the normalization to `query` for `useSubscription` as well and/or expose the [`normalizeQuery` function](https://github.com/logaretm/villus/blob/5da091967ca59d458b920d5a1236b89826f50605/packages/shared/src/utils.ts#L4-L17) so it can be easily used within the `subscriptionForwarder` as well? 

I'd gladly open a pull request, if so.

Thanks!

**Comment by logaretm** [comment]
This is indeed a bug. I think it could be fixed inside `handleSubscription.ts`

something like this:

```ts
    const normalizedQuery = normalizeQuery(operation.query);
    if (!normalizedQuery) {
      throw new Error('A query must be provided.');
    }

    useResult(forward({ ...operation, query: normalizedQuery }) as any, true);
```

Feel free to PR, otherwise, I will PR it tomorrow.
