### ISSUE TITLE
The Pinia Example preview: "Loading..."

### ISSUE THREAD

**Issue by dsbw** [logaretm/villus#204]
Tried [this page](https://villus.logaretm.com/examples/state-store-pinia/) on Brave and Chrome, enabled third-party cookies, and in both cases the preview hangs with a white screen that says "Loading..."

![screenshot](https://github.com/logaretm/villus/assets/4042938/cba1387b-aadb-4928-870e-79eca44c9fc1)

**Comment by logaretm** [comment]
The example was corrected, thanks for pointing this out.
