### ISSUE TITLE
gql.tada

### ISSUE THREAD

**Issue by sander-struijk** [logaretm/villus#206]
gql.tada works great with urql which I read Villus is based on, does it support it?

**Comment by logaretm** [comment]
Not at the moment, but it is planned. I just need to read up on how to add support for it since it probably doesn't use the same types used by GQL generator.

**Comment by logaretm** [comment]
3.4 should be now supporting `gql.tada`!

**Comment by sander-struijk** [comment]
That was quick! Thanks dude! 🤜

fre. 1. mar. 2024 kl. 13:34 skrev Abdelrahman Awad ***@***.***
