### ISSUE TITLE
Fetching on focus

### ISSUE THREAD

**Issue by brandonpittman** [logaretm/villus#23]
Would you consider adding a PR that implemented automatic refetching whenever was refocused?

**Comment by logaretm** [comment]
It depends on what do you mean by focus, you can always run the ‘execute’ function once the element gets focus.

**Comment by brandonpittman** [comment]
@logaretm swrv revalidates the cache every time the user refocuses the window, using the pageVisibility API. Would you be open to including that feature in villus' core? I'd be happy to work on it, just wanted to see if you're okay with that in the core library before I do any work on it.
