### ISSUE TITLE
Query Batching error [Wordpress graphql]

### ISSUE THREAD

**Issue by stephanedemotte** [logaretm/villus#26]
Hello i try to use query batching with worpdress graphql but i got a error `CombinedError`

When i don't use the `batcher()` i see 2 call with no error

<img width="671" alt="Screen Shot 2020-04-13 at 11 34 56 AM" src="https://user-images.githubusercontent.com/2158130/79134109-2b5a2980-7d7b-11ea-9ea7-385a12d18148.png">

When i activate it 
```
    useClient({
      url: '/cms/graphql',
      fetch: batcher()
    })
```
I see the call, the response seem to be good, an array of 2 objects

<img width="670" alt="Screen Shot 2020-04-13 at 11 34 28 AM" src="https://user-images.githubusercontent.com/2158130/79134214-55abe700-7d7b-11ea-8181-745d3e46630a.png">

But i get an error on each component response.

<img width="642" alt="Screen Shot 2020-04-13 at 11 33 53 AM" src="https://user-images.githubusercontent.com/2158130/79134305-7c6a1d80-7d7b-11ea-9c3d-800b0bdbc1e6.png">

Do you have an idea of who we can fix that ? A villius issue or wp-graphql issue ?

Thanks

**Comment by logaretm** [comment]
To my knowlege `wp-graphql` supports query batching, so it should work.

Could you share a live version of your API? It looks like the request was successful but Villus code threw an error regardless.

**Comment by stephanedemotte** [comment]
here 

http://origin-wp.demotte.net/cms/graphql

```
{
  pages {
    nodes {
      title
    }
  }
}
```

**Comment by stephanedemotte** [comment]
@logaretm Do you see the same error ?

**Comment by logaretm** [comment]
Sorry for the delay, this is indeed a bug. I've found the issue and will tag a release shortly.

**Comment by logaretm** [comment]
`0.4.2` and `1.0.0-alpha.6` were released with this fix.

**Comment by stephanedemotte** [comment]
yeah !

**Comment by stephanedemotte** [comment]
@logaretm I'm trying to use villus with vue 3 now.

I've got an error with batcher.

Without batcher the data is good, with the batcher i've got an error

<img width="653" alt="Screen Shot 2020-07-29 at 12 12 03 PM" src="https://user-images.githubusercontent.com/2158130/88824763-c0e7c080-d194-11ea-859e-04b3385921f4.png">


It's weird because, the date is here in the response, but villus throw an error.

You can test here : http://origin-wp.demotte.net/cms/graphql

```
const { data, error, done } = useQuery({ query: computed(() => `{ allSettings { generalSettingsUrl } }`) })
```

thanks !!!
