### ISSUE TITLE
Allow direct use of client

### ISSUE THREAD

**Issue by BenoitRanque** [logaretm/villus#28]
Allowing the client to be provided to useQuery, useMutation, and useSubscription would allow the use of multiple clients in the same context, something not currently possible.

The api would look like this:
```
    const client = createClient({
      url: '/graphql' // your endpoint.
    });
    const { data } = useQuery({
      client,
      query: '{ todos { text } }'
    });
```

**Comment by logaretm** [comment]
Available as of alpha releases here:

https://logaretm.github.io/villus/api/client/#using-the-client-manually
