### ISSUE TITLE
Feature request: Support for cache-only policy

### ISSUE THREAD

**Issue by pimlie** [logaretm/villus#30]
I am showing a list that gets lazy loaded after an Intersection Observer is triggered. When a visitor navigates away from this list, but then hits the back button I would like to repopulate all data that already exists in the local cache. But if it doesnt exists in the cache yet, I would like to wait until the Intersection Observer is triggered before loading the data over the network again.

This policy doesnt seem to be supported yet, or do you prefer we track / fix this in userland?

**Comment by logaretm** [comment]
So it shouldn't hit the network at all unless explicitly called?

**Comment by pimlie** [comment]
The first approach I was thinking about was just setting `cachePolicy: cache-only` initially, then after the component is mounted remove the explicit cachePolicy on the executeQuery call so it will request from the network when executed. Not sure if this approach makes sense though?
