### ISSUE TITLE
Question: How to include cookies in request?

### ISSUE THREAD

**Issue by MarvinRudolph** [logaretm/villus#35]
Hey!

How can I include cookies/credentials in the request?
With Apollo, it works with `credentials: "include"` but what's the equalivient with villus?

**Comment by logaretm** [comment]
`villus` passes fetch options to the underlying `fetch()`, so similar to headers you can also use `credentials: "include"`

https://logaretm.github.io/villus/guide/headers.html#headers

```js
const client = createClient({
  endpoint: '/graphql',
  context: () => {
    return {
      fetchOptions: {
		credentials: "include"
      }
    };
  }
});
```

**Comment by orjellingsen** [comment]
> `villus` passes fetch options to the underlying `fetch()`, so similar to headers you can also use `credentials: "include"`
> 
> https://logaretm.github.io/villus/guide/headers.html#headers
> 
> ```js
> const client = createClient({
>   endpoint: '/graphql',
>   context: () => {
>     return {
>       fetchOptions: {
> 		credentials: "include"
>       }
>     };
>   }
> });
> ```

Hi, this does not seem to work anymore, and I cant find any other examples on how to include credentials from a cookie. Any help on this would be greatly appreciated.
