### ISSUE TITLE
Query Batching error [Wordpress graphql] [vue3]

### ISSUE THREAD

**Issue by stephanedemotte** [logaretm/villus#36]
Hello @logaretm I'm trying to use villus with vue 3 now.

I've got an error with batcher.

Without batcher the data is good, with the batcher i've got an error

<img width="653" alt="Screen Shot 2020-07-29 at 12 12 03 PM" src="https://user-images.githubusercontent.com/2158130/88838104-0d3bfc00-d1a7-11ea-8cae-efa32b2bb3d8.png">

It's weird because, the data is here in the response, but villus throw an error.

You can test here : http://origin-wp.demotte.net/cms/graphql

```
import { computed } from 'vue'
import { useClient, batcher, useQuery } from 'villus'

useClient({
  url: 'http://origin-wp.demotte.net/cms/graphql/cms/graphql',
  fetch: batcher()
})
const { data, error, done } = useQuery({ query: computed(() => `{ allSettings { generalSettingsUrl } }`) })
```

If you remove fetch: batcher() it's ok

thanks !!!

**Comment by stephanedemotte** [comment]
@logaretm ping

**Comment by logaretm** [comment]
Hello, this should be fixed in `alpha.6`, I tried it now and it works fine.
