### ISSUE TITLE
Cannot detect villus client - useMutation

### ISSUE THREAD

**Issue by JoshuaLowe1002** [logaretm/villus#45]
Great work on this project, super handy!

I've successfully got queries to work however I am having issues with mutations, I get the following error:
![image](https://user-images.githubusercontent.com/25752941/94283018-68406400-ff48-11ea-8df2-652b2c9adc78.png)

Here's my setup:

Use client within app.vue - 
![image](https://user-images.githubusercontent.com/25752941/94283118-85753280-ff48-11ea-9141-73d76b912939.png)

A typescript file that has a createProduct function - 
![image](https://user-images.githubusercontent.com/25752941/94283181-99209900-ff48-11ea-8783-ea343c8c6b13.png)

Then, I am calling createProduct on button press from within a vue file. 

Not sure what i'm doing wrong here but any pointers would be greatly appreciated!

**Comment by logaretm** [comment]
I suspect that `useMutation` is not being called in a setup function, do you mind sharing the component's full code?

**Comment by JoshuaLowe1002** [comment]
hI @logaretm,

Here's the component code: 

```
<template>
  <button @click="createProduct('Hello', 'World')">Submit</button>
</template> 

<script lang="ts">
import { reactive, watch, compile, ref, onBeforeMount } from 'vue'

import UseProducts from '../use/useProducts'

import {createProductMutation} from '../mutations/createProductMutation'
import { useMutation } from 'villus';

export default {
  name: 'Form',
  setup() {

    const { getProducts, createProduct } = UseProducts();

    const products = getProducts();

    const { data, execute } = useMutation(createProductMutation);


    return {
      data, products, createProduct, execute
    }
  }
}
</script>```

Thanks!

**Comment by logaretm** [comment]
I can't tell from that snippet as everything seems to be in order. Is `useProudcts` by any chance is also using `useMutation` inside it?
