### ISSUE TITLE
Don't require query objects to have a loc property

### ISSUE THREAD

**Issue by pipe01** [logaretm/villus#52]
I'm using [GraphQL code generator](https://graphql-code-generator.com/) with the [typed document node](https://github.com/dotansimha/graphql-typed-document-node) plugin. This plugin exports an object that looks like `Object { kind: "Document", definitions: (1) […] }`, which is an issue since [here](https://github.com/logaretm/villus/blob/a9a2b3710460e67355b9bcd059e8db622627eda7/packages/villus/src/utils/query.ts#L13) the `normalizeQuery` function expects the query object to have a `loc` property. This can be worked around by doing `TheQueryDocument.loc = {}`, so I think the requirement could be dropped altogether and instead check for a property like `kind`.

**Comment by logaretm** [comment]
closed by #53
