### ISSUE TITLE
Call is make 2 time if suspense & batcher

### ISSUE THREAD

**Issue by stephanedemotte** [logaretm/villus#56]
Hello

When i use suspense & batcher, the call is made 2 time.
Once  when the component load, another when the component is mounted.

Thanks !

**Comment by logaretm** [comment]
Thank you for reporting this, could you please more information?

Which flavor are you using `useQuery` or `Query` component? and could you replicate the issue on codesandbox or even a repo.

**Comment by stephanedemotte** [comment]
Here the  [git repro](https://github.com/stephanedemotte/test-villius-bach-suspense) and a [video](https://streamable.com/t8fhpc)

Thanks !

**Comment by logaretm** [comment]
Thank you for reporting this, I have identified the issue thanks to your example and fixed it. Will be tagged shortly in the next release.
