### ISSUE TITLE
Add response headers to afterQuery plugin function

### ISSUE THREAD

**Issue by juan267** [logaretm/villus#62]
First thanks a lot for this beautiful package. 

My issue is that Im using [Devise auth token](https://github.com/lynndylanhurley/devise_token_auth) as my JWT backend strategy. As a safety measure they change the token after each request and sent back the new token on a `response` header. So I need to get that header to update the token for the next request. 

I currently have something like this. But the `opContext.headers['access-token']` is using the request token not the response one. It would be nice to have access to the response properties (response opContext) in afterQuery.

```js
function afterwareAuth({ afterQuery, opContext }: ClientPluginContext) {
  afterQuery(() => {
    console.log(opContext.headers)
    auth.setAuthStorageTokens({
      // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
      // @ts-ignore
      accessToken: opContext.headers['access-token'],
      // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
      // @ts-ignore
      client: opContext.headers.client,
      // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
      // @ts-ignore
      expiry: opContext.headers.expiry,
      // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
      // @ts-ignore
      uid: opContext.headers.uid
    })
  })
}
```

Thanks for you help!

**Comment by logaretm** [comment]
Having access to the fetched response is definitely something I considered, will see what I do.

**Comment by dcarniel-evorra** [comment]
Hi,

I'm trying to use this as explained here: https://villus.logaretm.com/guide/plugins#example---adding-authorization-headers

Though I never get any header in the response. I'm wondering if there would be an issue somewhere else in the code that prevents this attribute of the response to be populated.

I'm using v1.0.1, my code is as follow:

`function authPlugin( { opContext, afterQuery }: ClientPluginContext ) {
  opContext.headers.Bearer = `${tokenFromStore.value}`;
  
  afterQuery((result, { response }) => {
    if (response && response.status == 200 && response.headers ) {
      console.log( response.headers.get( 'jwt-token' ) )
    }
  });
}`

I've tried to log the full "response.headers" object, it looks like some kind of map but no data in it. And I can see from the browser network log that there are many headers.

**Comment by dcarniel** [comment]
Hi,

I've tried to access headers through a plugin as described in: https://villus.logaretm.com/guide/plugins#example---adding-authorization-headers

Though I never get any header, whereas the browser network log shows many.

My code is as follow:

`function authPlugin( { opContext, afterQuery }: ClientPluginContext ) {
  opContext.headers.Bearer = `${tokenFromStore.value}`;
  
  afterQuery((result, { response }) => {
    if (response && response.status == 200 && response.headers ) {
      console.log( response.headers.get( 'jwt-token' ) )
    }
  });
}`
