### ISSUE TITLE
[TypedDocumentNode] No auto complete on variable

### ISSUE THREAD

**Issue by Stevenje** [logaretm/villus#68]
Version : Beta 8

Can't seem to get auto complete to work on variables
![image](https://user-images.githubusercontent.com/4363358/96741714-ba2dab80-1387-11eb-9823-82a72f1990a2.png)

![image](https://user-images.githubusercontent.com/4363358/96741809-dd585b00-1387-11eb-917d-7f68fb8f17ed.png)

Works fine for returned data
![image](https://user-images.githubusercontent.com/4363358/96741730-c0238c80-1387-11eb-9b70-ef1027983a55.png)

`export const UserDocument: DocumentNode<UserQuery, UserQueryVariables> = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"user"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"where"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UserWhereUniqueInput"}}},"directives":[]}],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"user"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"where"},"value":{"kind":"Variable","name":{"kind":"Name","value":"where"}}}],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"email"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"id"},"arguments":[],"directives":[]}]}}]}}]};`

Thanks for all your great work!

**Comment by logaretm** [comment]
I see that it's confusing the two signatures, this is an issue not related to the `TypedDocument`. Will see what I can do.

**Comment by Stevenje** [comment]
Thanks! There also seems to be a weird bug with autocomplete removing the dot after an option has been selected. 

![image](https://user-images.githubusercontent.com/4363358/96747910-7e4a1480-138e-11eb-8fd3-8b97a286a739.png)

![image](https://user-images.githubusercontent.com/4363358/96747937-86a24f80-138e-11eb-882d-5e7d28a8b9b0.png)

**Comment by logaretm** [comment]
Don't think that's a `villus` issue. For the first one, I was avoiding this for a whole but looks like a major upgrade is in order. The signatures need to be updated so it doesn't confuse the `DocumentNode` with `QueryComposableOptions`.

Basically all `useQuery`, `useMutation` and `useSubscription` signatures will follow this scheme:

1. first argument is always `query`
2. second argument is always `variables`
3. third argument is always `options` where applicable

Will tag this as `rc.0` once done

**Comment by logaretm** [comment]
Closed in `rc.0`, documentation was updated to reflect the chosen signature which is:

```js
useQuery({
  query: Posts,
  variables: {},
  // other options
});

useMutation(CreatePost);

useSubscription({
  query: ChatMessages,
  variables: {}
}, reducer);
```

**Comment by Stevenje** [comment]
@logaretm Looks to be working great. Thanks a lot, much appreciated.
