### ISSUE TITLE
[Subscriptions] SubscriptionClient module not found, despite install. 

### ISSUE THREAD

**Issue by Stevenje** [logaretm/villus#69]
Setup: Vite, Villus Beta 8

I've installed `subscriptions-transport-ws` but keep getting this error in chrome. Potentially could be related to the Vite build process. 

![image](https://user-images.githubusercontent.com/4363358/96767014-8f505100-13a1-11eb-98a1-d47a2b48076e.png)

``` ts
<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <HelloWorld />
</template>

<script lang="ts">
import HelloWorld from "./components/HelloWorld.vue";
import { SubscriptionClient } from "subscriptions-transport-ws";
import { useClient, handleSubscriptions, defaultPlugins } from "villus";

const subscriptionClient = new SubscriptionClient(
  "ws://xxxxx/graphql",
  { reconnect: true },
);

const subscriptionForwarder = (operation: any) =>
  subscriptionClient.request(operation);

export default {
  name: "App",
  components: {
    HelloWorld,
  },
  setup() {
    useClient({
      url: "https://xxxxx/graphql",
      use: [handleSubscriptions(subscriptionForwarder), ...defaultPlugins()],
    });
  },
};
</script>
```

**Comment by logaretm** [comment]
This is not related to villus so I'm closing this. Please check `subscriptions-transport-ws` compatibility with vite

**Comment by Stevenje** [comment]
Hey @logaretm I appreciate that, are you able to recommend a substitute library in the interim? Also I do think testing Villus with Vite would be good going forward as Villus is targeted at Vue 3 users and Vite seems to be the upcoming standard for developing with it.

**Comment by Stevenje** [comment]
confirmed issue is Vite, project works when built for production although yarn dev is broken
