### ISSUE TITLE
Context option missing from useClient

### ISSUE THREAD

**Issue by Stevenje** [logaretm/villus#71]
![image](https://user-images.githubusercontent.com/4363358/96921812-a2802100-1474-11eb-94ed-351568f64f33.png)

**Comment by logaretm** [comment]
The context was deprecated a while go

**Comment by gawlk** [comment]
Hi !

You might want to update the documentation then.

![Screen Shot 2020-10-30 at 12 08 46 PM](https://user-images.githubusercontent.com/32246972/97698360-b2b58300-1aa8-11eb-92d2-de696aef5331.png)

**Comment by logaretm** [comment]
@gawlk Thank you, should be updated shortly.
