### ISSUE TITLE
Question on cache-and-network policy

### ISSUE THREAD

**Issue by geekox86** [logaretm/villus#76]
Greetings, thank you for the awesome library. Good job there 👍🏼.

Does cache-and-network update the reactive data returned by useQuery when network fetch is resolved?

**Comment by logaretm** [comment]
No, it doesn't at the moment. Maybe in the future or I might add a new strategy just for that.

**Comment by logaretm** [comment]
> I can't see why you wouldn't have the new data be available immediately.

I don't mind having it, PRs are welcome. I just haven't had the time to work on it yet.

**Comment by develar** [comment]
Current behaviour also not expected for me. https://v4.apollo.vuejs.org/guide-composable/query.html#fetch-policy

> return result from cache first (if it exists), then return network result once it's available.

So, will be great if villus will also act like that.

**Comment by logaretm** [comment]
Took long enough to implement this, I've added this in `rc.19`.
