### ISSUE TITLE
How to handle custom scalar types like Date?

### ISSUE THREAD

**Issue by geekox86** [logaretm/villus#77]
Hi again,

How can I handle custom scalar types returned by my queries like Date fields?

Thank you.

**Comment by logaretm** [comment]
What do you mean "handle" them? I don't think this relevant to villus.

**Comment by geekox86** [comment]
Hi @logaretm. I mean convert them to JS Date objects after receiving the results from the server. Is this possible?

**Comment by logaretm** [comment]
Unfortunately, villus does not offer data mapping utilities for custom scalars at this time. You will need to do this at the application level instead.
