### ISSUE TITLE
Export VILLUS_CLIENT symbol

### ISSUE THREAD

**Issue by lewebsimple** [logaretm/villus#80]
It could be useful to export the `VILLUS_CLIENT` symbol in order to access the provided client from other composable functions.

**Comment by logaretm** [comment]
May I ask why do you need access to the injected client, what is your usecase? You may use the result of `useClient` to gain access to the client instance instead.

**Comment by lewebsimple** [comment]
I call `useClient` from `onGloablSetup` in Nuxt (it could also be the top-level component setup), but say I want to encapsulate some GraphQL query inside a composable like `useSomeQuery` and possibly transform the data, where do I get the client from?
It seems to me calling useClient multiple times would create many instances of the Villus client, is that correct ?

**Comment by logaretm** [comment]
Yes it would create several clients. But I'm not sure you need to do that, I do use nuxt/composition-api in a production app with tons of GraphQL queries but didn't seem to encounter your use-case.

I do have a lot of data transforms, but I use `computed` for that. For example:

```js
function useProduct(id) {
  const { data, isFetching } = useQuery({
    query: ProductQuery,
    variables: { id }
  });

  const product = computed(() => {
    return data.value?.products[0];
  });

  return {
    product,
    isFetching
  };
}
```

**Comment by lewebsimple** [comment]
What if I want to share that computed property across several components ?

**Comment by logaretm** [comment]
I usually either pass it via props if it's just 1 level deep or use `provide/inject` there, so I actually have something like this as well:

```js
const product = computed(() => {
  return data.value?.products?.items[0];
});

provide('PRODUCT_CTX', product); // I use a symbol here, but strings work fine

// later on in a deeply nested child
const product = inject('PRODUCT_CTX');

product.value; // access query value
```
