### ISSUE TITLE
Registering client as a plugin

### ISSUE THREAD

**Issue by sibbng** [logaretm/villus#81]
Hi, I'm using Vue 3. I want to install villus but I dont have a root component and don't want to use useClient on every component. Is installing villus as a plugin possible?

```js
const app = createApp()

const client = createClient({ url: '...' });

app.use(client)
```

**Comment by logaretm** [comment]
You don't have to use it in every component, just call `useClient` in the root `App` component.

```js
// App.vue
{
  setup() {
    useClient({ url: '...' });
  }
}
```

**Comment by sibbng** [comment]
Oh, right. Of course I have App.vue. But actually I don't have any data logic in App.vue and keeping this stuff in here kinda anti-pattern for me. This is totally my opinion.

When we look at the ecosystem (Vue-Router, Vuex, Vue-Apollo), most of them does it with a plugin. I thought providing a another way of registering Villus should be nice to have. If you are totaly okay with that, I can make a PR. Probably it will just take 3 lines of code. I thinking naming it like `createVillus`.

**Comment by logaretm** [comment]
Well, I would disagree. But I don't mind adding that to the library for convenience, feel free to PR it and I would love to accept it.
