### ISSUE TITLE
@villus/batch causes uncaught exception in Promise

### ISSUE THREAD

**Issue by zigomir** [logaretm/villus#86]
`villus` performs `await fetch` inside `try ... catch` block while `batch` does not. This causes uncaught promise exception.

Imo it would be nice if `@villus/batch` would also handle this case and return `CombinedError`.

**Comment by logaretm** [comment]
What kind of errors are you looking to catch? fetch exceptions? If you could create an example that would be great, you can use [codesandbox](https://v3.vue.new)

**Comment by zigomir** [comment]
@logaretm yes, fetch exceptions. This is the [reproduction repository](https://github.com/zigomir/villus-batch) and this is [codesandbox](https://codesandbox.io/s/hardcore-spence-w2h45?file=/src/main.js).

Codesandbox isn't perfect environment for reproduction, because you need to set network=offline in Chrome dev tools while checking the console.

I explain the issue in https://github.com/zigomir/villus-batch/blob/master/src/main.js#L9-L11 and https://github.com/zigomir/villus-batch/blob/master/src/main.js#L29

I'd expect to get `response.error` back, like without `batch` plugin. But instead you get `Uncaught (in promise)` error.

If you want, I can try to fix this, but might need some guidance along the way.

**Comment by logaretm** [comment]
Fixed in `@villus/batch` release `rc.3`

**Comment by zigomir** [comment]
@logaretm works great, thank you very much 💯
