### ISSUE TITLE
Set headers after client creation, or per request?

### ISSUE THREAD

**Issue by danrocha** [logaretm/villus#9]
Hope this is not too much of an edge case:

Trying to use Villus in a **Vuex** store module in a **Nuxt** app.

This works, if I do **not** need to pass `Authorization` headers:

```js
// myStoreModule.js
import { createClient } from 'villus'

const client = createClient({
  url: 'http://localhost:4000/graphql'
})
// ...
export const actions = {
  async fetchData({ commit, dispatch }) {
    const data = await client.executeQuery({
      query: BOARD_QUERY
    })
    commit('SET_BOARD', data)
  }
}
```

However, I do need to pass `Authorization` headers. But in the Vuex store, I can only access the original headers from the `http.request` object inside of actions. Therefore, I cannot do:

```js
const client = createClient({
  url: 'http://localhost:4000/graphql',
  context: () => {
    return {
      fetchOptions: {
        headers: {
          Authorization: TOKEN
        }
      }
    };
  }
})
```
...because I do not have access to TOKEN outside of my actions.

Therefore, I would like to do something like this:

```js
export const actions = {
  async fetchData({ commit, dispatch }, { req }) {
	// first get TOKEN from original request
    const token = getToken(req.headers)
	// the set the token to the previously created client
    client.context = () => {
      return {
        fetchOptions: {
          headers: {
            Authorization: TOKEN
          }
        }
      }
    }
	//...
}
```
But this does not work. So, how would you go around this issue?

With Axios, I could easily modify the headers on each request. Would something like that be possible with Villus client?

**Comment by logaretm** [comment]
Your method should work, I'm not sure about the problem. I'm overhauling the extension API, I haven't settled yet on the final draft but It looks like this:

```js
client.beforeFetch(({ headers }) => {
  headers.Authorization = 'Bearer ....';
});

client.afterFetch(({ response }) => {
  // Do something with the response.
});
```

My goals are to allow retries, caching, error handling with simple API like that.

**Comment by MarcelloTheArcane** [comment]
I'd need to be able to change headers on-the-fly too. @logaretm how do you anticipate it would work with subscriptions?

**Comment by danrocha** [comment]
@logaretm indeed it works now. My mistake.

Vuex cannot receive `req` in the actions; I had to use [nuxServerInit](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action) to the the token, then use it in my action as I wrote above.

Looking forward to updates. Loving the library so far!

**Comment by altitudems** [comment]
I would like to add to this request by asking that the context function support promises. This way we could first get an access token asynchronously, and then update headers and execute the query.

**Comment by BenoitRanque** [comment]
I have a requirement similar to this, where I need to set a header per request. I don't think it's possible at the moment, could this feature be implemented in the future? I think I could manage a pull request if this is something we are interested in.

**Comment by logaretm** [comment]
@BenoitRanque It's something that would be implemented but sadly I didn't have time to properly implement such an API.

Feel free to write a proposal and depending on the conversation you could PR it,.
