### ISSUE TITLE
Ability to use subscriptions outside of component

### ISSUE THREAD

**Issue by zigge** [logaretm/villus#91]
I have a use-case where I need to wrap the `useSubscription` function in a class, that lies outside of a component scope. I was wondering if there is a way to handle unsubscribing to a subscription ? I can see that you handle it, in a component context, but it would be nice to have the ability to manually unsubscribing from a subscription. 
Otherwise great lib!

**Comment by logaretm** [comment]
You could still use `useSubscription` inside a class as long as it's being instantiated inside a `setup` function.

Otherwise, doesn't the raw client instance work for your needs?
