### ISSUE TITLE
async setup() failing to inject villus after first await

### ISSUE THREAD

**Issue by staticglitch** [logaretm/villus#92]
Hello,

I have a simple situation when I want to prefetch data in a component, and then also allow mutation in that same component by executing a form. If I do `async setup()` and `await useQuery()`, then the following `useMutation` fails to recognize villus client. 

```javascript
export default {
   async setup() {
           
      const { data } = await useQuery(`...`);
     
      const { execute } = useMutation(`...`);

   }
};
```

The `useMutation()` produces: `Uncaught (in promise) Error: Cannot detect villus Client, did you forget to call 'useClient'?`

If I remove `async/await` it all works correctly. I'm assuming this is related to vue's setup lifecycle, but I can't figure it out from the docs - is this likely my error or a bug?

The intended use is with `<suspense>` one level above. I understand I could have a workaround in this component by using `{ isFetching }` on the `useQuery` and show a fallback that way.

**Comment by logaretm** [comment]
We have a live example for that case and it seems to be working fine:

https://villus.logaretm.com/examples/suspense/

Could you re-create this in a code sandbox? You can use a live free graphql API [like this one](https://pet-library.moonhighway.com/).

**Comment by staticglitch** [comment]
Here's the codepen: https://codepen.io/staticglitch/pen/abmMROm

The only thing I changed is this:

```javascript
 
    const { data } = await useQuery({
      query: AllPets
    });
    // Simulate slow network
    await sleep(3000);
    
    //added
    const { data: dataSecond } = useQuery({
      query: AllPets
    });

    return { data, icons };
```

**Comment by logaretm** [comment]
Okay this looks like a Vue bug, if you swap the two `useQuery` call it will work fine. I guess the `await` is causing an issue here with detecting the active component? There is hardly any documentation on suspense yet so I would treat it as experimental as it says in the console.

For now, you could make sure to `await` at the very end.

```js

// added this
const { data: dataSecond } = useQuery({
  query: AllPets
});

const { data } = await useQuery({
  query: AllPets
});
```

**Comment by staticglitch** [comment]
Yeah, looks like `await` breaks it, even if used on `await console.log(1)`, but it all works if all `inject`'s happen before it. A bit sketchy.

**Comment by staticglitch** [comment]
For completeness sake in case anyone stumbles here... This is not a bug and inject simply doesn't work after `await`, reference: 

https://forum.vuejs.org/t/vue-3-inject-can-only-be-used-inside-setup-or-functional-components/108672/4
