### ISSUE TITLE
Subscription pause and resume problem

### ISSUE THREAD

**Issue by ghost-void** [logaretm/villus#94]
```
{pause, resume} = useSubscription({query: Something})

pause()
resume()
pause()
resume()
pause()
resume()
```

The resume function will create a new subscription, and restart previous subscription. There are multiple subscriptions be subscribed at the same time.

**Comment by logaretm** [comment]
Thank you for reporting this, you should note that villus does not manage your websocket connection and you should configure your subscription forwarder to disconnect after inactivity which is supported with `ws-subscribptions-transport` pkg.

Having said that, I have tweaked the pausing behavior to not unsubscribe and to just ignore the results until it is resumed again which should address your issue.

Still you may encounter this when `query` or `vars` are reactive and change frequently.

**Comment by ghost-void** [comment]
Because some UI like ionic-vue, it only calls onMounted at first time, and not call onBeforeUnmount, may be the component is in keep-alive. 

I have to pause subscription by myself, but the resume is a problem.

I found the key point, if resume multiple times without pause, it will make a new subscribe with new id, even if the previous subscribe is not paused.

**Comment by ghost-void** [comment]
Maybe do some check in resume if it is not paused, because in some situation onMounted will be called multiple times, but onBeforeUnmounted not.

**Comment by logaretm** [comment]
`useSubscription` cannot check if an observer is `live` or not, this is the responsibility of the subscription client you use.

I have released `rc.11` with the tweak I mentioned.

**Comment by ghost-void** [comment]
I think useSubscription should export a `stop` function to do `observer.unsubscribe()` by user.

And add a unsubscribe to onMounted, because this hooks can be called multiple times, without onBeforeUnmounted.
```
  onMounted(async () => {
    if (observer) {
      observer.unsubscribe();
    }

    observer = await initObserver();
  });
```

**Comment by logaretm** [comment]
> I think useSubscription should export a stop function

That implies we should also have a `start` or an `execute` function. Also a boolean to indicate if the subscription is active or not, and probably an option to pass if it should subscribe on mounted or not similar to queries.

> And add a unsubscribe to onMounted, because this hooks can be called multiple times

Sounds reasonable

**Comment by ghost-void** [comment]
Exactly!
