### ISSUE TITLE
How to setup with Nuxt?

### ISSUE THREAD

**Issue by secretlifeof** [logaretm/villus#98]
Hello.

I like the API you have build. Hope you might help me. I don't understand how to set Villus up with Nuxt. Have read #10. I am completely new to Vue and Nuxt. Setting up a plugin like the one below, also using a provider inside layouts/default.vue shows the same error:

> [Vue warn]: Error in data(): "Error: Could not resolve a fetch() method, you should provide one."

Both Chrome and Node.js has fetch as far as I can tell.

#### Plugin
```javascript
// plugins/api.js
import { onGlobalSetup, provide } from '@nuxtjs/composition-api'
import { useClient, defaultPlugins, fetch } from 'villus'

export default function ({ app, $config, query }) {
  // onGlobalSetup(() => {
  //   useClient({
  //     url: $config.apiUrl,
  //     use: [...defaultPlugins()],
  //   })
  // })

  app.setup = () => {
    useClient({
      url: $config.apiUrl,
    })
  }
}
```

#### Component
```javascript
// component.vue
export default defineComponent({
  setup() {
    const query = `
      entries(section: "general") {
        ... on general_general_Entry {
          id
        }
      }

    `
    // @ts-ignore
    const { data } = useQuery(query)

    return { data }
  },
})
```

How would you setup Villus in Nuxt? What am I doing wrong?

### Versions
"villus": "^1.0.0-rc.12",
"graphql": "^15.5.0",
"@nuxtjs/composition-api": "^0.20.1",
"nuxt": "^2.14.12",

**Comment by logaretm** [comment]
Hello, Nuxt runs your application in two environments:

- Node.js
- Browser

Because of this, you need to provide a fallback for both environments in case `fetch` is not supported there.

Generally, because most browsers already have support for `fetch`, you only need to worry about `Node.js`, you can do that with `node-fetch`.

So install `node-fetch` in your dependencies and add this:

```
global.fetch = require("node-fetch");
```

To your nuxt.config.js, and it should work fine.

there is an example here:

 https://codesandbox.io/s/villus-nuxt-typeddocument-plugin-qewsn?from-embed=&file=/nuxt.config.js:0-38

**Comment by secretlifeof** [comment]
Thanks for your very quick reply! That removed the fetch error. Still have another error in my console.

> Uncaught (in promise) Error: A query must be provided.
    at makeFetchOptions (villus.esm.js?9ada:267)
    at fetchPlugin (villus.esm.js?9ada:227)
    at Client.execute (villus.esm.js?9ada:337)
    at async execute (villus.esm.js?9ada:436)

How can I fix this error? Have tried versions villus_rc0 (used in your codesandbox) and villus_rc12.

This is my __tsx__ file. Have tried it with and without graphql-tag. Tried to setup a codesandbox with babel-preset-vca-jsx and my tsconfig.js but I was still not able to add tsx files.

```javascript
import { useQuery } from 'villus'
import { defineComponent } from '@nuxtjs/composition-api'
import gql from 'graphql-tag'

export default defineComponent({
  setup() {
    const EntryQuery = gql`
      query GetEntry {
        entries(section: "general") {
          id
        }
      }
    `

    // @ts-ignore
    const { data, isFetching } = useQuery(EntryQuery)

    return <div>{JSON.stringify(data)}</div>
  },
})
```

console.log data returns
> data:  RefImpl {} and value: null

**Comment by logaretm** [comment]
Looks like you are using an older syntax of villus, the query must be provided in an object:

```js
const { data, isFetching } = useQuery({
  query: EntryQuery // 👈
})
```

**Comment by secretlifeof** [comment]
Thanks a lot! Now it's working.

Yes I googled Villus and ended up here https://logaretm.github.io/villus/guide/queries but should have looked at https://villus.logaretm.com/guide/queries. Maybe you can remove that old URL?

**Comment by logaretm** [comment]
Yea, I will setup a redirect. Thanks
