### ISSUE TITLE
@villus/multipart body map doesn't include additional variables

### ISSUE THREAD

**Issue by tbarkley** [logaretm/villus#99]
In multipart when constructing new FormData(), the map doesn't include other variables passed in;
For example;
```javascript
this._multiPartClient.executeMutation({
      query,
      variables: {
              _id:id,
                file: file
       }
})

//multipart.esm.js
//In this case, _id is not mapped. 

/**
Map is like this;
---------------------------------------------------------
map='{ "file": ["variables.file"] }' 
instead of 
map='{ "file": ["variables.file"], "_id": ["variables._id"] }'
*/
const map = {};
let i = 0;
files.forEach(paths => {
     map[++i] = paths.map(path => `variables.${path}`);
});
body.append('map', JSON.stringify(map));

**Comment by logaretm** [comment]
According to [the spec](https://github.com/jaydenseric/graphql-multipart-request-spec/issues/44), only the files should be on the `map`, other values will exist in the `operations` object/payload.

You should probably mention which server implementation you are using, I just tested this on an `apollo-server@2.7` and it works fine. If you can provide an example with both a clientside and server-side implementation that would help a alot.

Closing for now until an issue is confirmed.

**Comment by tbarkley** [comment]
@logaretm first if all, thank you very much for your work. It's very good. I saw that the spec doesn't specify how to handle this (I now will raise the question with the creator of that spec). 

I wanted to find the correct way this should be handled since I wasn't seeing the extra variables being sent to the serve me but found that if I change your implementation slightly, it would work. 

Please see the example in this article on how I expected it to work; https://medium.com/@vcomposieux/handle-file-uploads-using-a-graphql-middleware-11914ba05bfc

$ curl http://localhost:8000/graphql \
-F operations='{ "query": "mutation DoUpload($file: Upload!, $title: String!) { upload(file: $file, title: $title) }",
"variables": { "file": null, "title": null } }' \
-F map='{ "file": ["variables.file"], "title": ["variables.title"] }' \
-F file=@myfile.txt \
-F title="My content title

**Comment by tbarkley** [comment]
@logaretm Please see the response from @jaydenseric here; https://github.com/jaydenseric/graphql-multipart-request-spec/issues/44#issuecomment-783136017

When I try to curl to my endpoint (indicating it's not a server issue) using the following, it works but not when adding variables using @villus/multipart;

{ "query": "mutation($file: Upload!, $_id: ID!) { singleUpload(file: $file, _id: $_id) { _id } }", "variables": { "file": null, "_id": "1234" } }

Maybe I'm using your library incorrectly? I'm doing the following using multipart client and I've confirmed that my ID is properly being added to variables;

```javascript
this._multiPartClient.executeMutation({
      query,
      variables: {
              _id:id,
                file: file
       }
})

**Comment by tbarkley** [comment]
@logaretm I may have had just one argument named incorrectly in my query. I was able to get it to work.

**Comment by logaretm** [comment]
Glad to hear it 🚀
